### PR TITLE
Support transformers stacks on handlers

### PR DESCRIPTION
**Pull request by serras**

### CODE REVIEW

**Comment by lucasdicioccio** [comment]
This is nice! I think the day I need to finally unlearn MonadBaseControl and learn UnliftIO has came. Thanks @serras

**Comment by serras** [comment]
My pleasure :)

**Comment by serras** [comment]
Do you think it would be possible to publish a new release of `warp-grpc` in Hackage? That way we could depend on it in [Mu](https://github.com/higherkindness/mu-haskell).

**Comment by lucasdicioccio** [comment]
@serras I think yes we can release.
Can you try publishing the new package? you should have the rights for `warp-grpc` as well.

**Comment by serras** [comment]
[Done](http://hackage.haskell.org/package/warp-grpc-0.4.0.0)!

**Pull request merged**
